version: '3.8'
services:
  build-app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms: 
        - "linux/amd64"
    image: "mmhk/bedrock-claude-proxy"

  bedrock-claude-proxy:
    image: "mmhk/bedrock-claude-proxy"
    restart: always
    volumes:
      - ./cache.db:/app/cache.db
    environment:
      API_KEY: "${API_KEY}"
      AWS_BEDROCK_ACCESS_KEY: "${AWS_BEDROCK_ACCESS_KEY}"
      AWS_BEDROCK_SECRET_KEY: "${AWS_BEDROCK_SECRET_KEY}"
      AWS_BEDROCK_REGION: "${AWS_BEDROCK_REGION}"
      AWS_BEDROCK_MODEL_MAPPINGS: "${AWS_BEDROCK_MODEL_MAPPINGS}"
      AWS_BEDROCK_DEBUG: false
      CACHE_BUCKET_NAME: "${CACHE_BUCKET_NAME}"
      CACHE_DEFAULT_EXPIRY_HOURS: "${CACHE_DEFAULT_EXPIRY_HOURS}"
      ZOHO_ALLOW_DOMAINS: "${ZOHO_ALLOW_DOMAINS}"
      ZOHO_CLIENT_ID: "${ZOHO_CLIENT_ID}"
      ZOHO_CLIENT_SECRET: "${ZOHO_CLIENT_SECRET}"
      ZOHO_REDIRECT_URI: "${ZOHO_REDIRECT_URI}"
      LOG_LEVEL: INFO
    ports:
      - "3010:3000"

  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    restart: unless-stopped
    ports:
      - "8080:8080"

  chatgpt-next:
    image: "mmhk/chatgpt-next-web"
    restart: always
    env_file:
      - .env
    ports:
      - "4002:3000"
