version: '3'
services:
  bedrock-claude-proxy:
    image: "mmhk/bedrock-claude-proxy"
    restart: always
    environment:
      API_KEY: "your-api-key"
      AWS_BEDROCK_ACCESS_KEY: "${AWS_BEDROCK_ACCESS_KEY}"
      AWS_BEDROCK_SECRET_KEY: "${AWS_BEDROCK_SECRET_KEY}"
      AWS_BEDROCK_REGION: "us-east-1"
      AWS_BEDROCK_MODEL_MAPPINGS: "${AWS_BEDROCK_MODEL_MAPPINGS}"
    ports:
      - "3000:3000"
  chatgpt-next:
    image: "yidadaa/chatgpt-next-web"
    restart: always
    environment:
      DEFAULT_MODEL: "claude-2.1"
      DISABLE_GPT4: 1
      HIDE_USER_API_KEY: 1
      DISABLE_FAST_LINK: 1
      ANTHROPIC_URL: "http://bedrock-claude-proxy:3000"
      ANTHROPIC_API_KEY: "your-api-key"
      ANTHROPIC_API_VERSION: "2023-06-01"
      CUSTOM_MODELS: "-all,+claude-2.1=claude-2.1(AWS bedrock),+claude-3-sonnet-20240229=claude-3.5-sonnet(AWS bedrock)"
    ports:
      - "4001:3000"